
# SEO settings
title: Las Vegas Python - Feb 2016
description: "Class site for the Las Vegas Python class in Feb of 2016"
keywords: "python, django, "
url: http://tiy-lv-python-2016-02.github.io
baseurl: null

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/simplest
disqus_shortname: ""

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 5
paginate_path: "/page/:num/"
comments: false

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Fernando Moreira
  job      : Frontend Engineer
  bio      : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb    : /images/author.jpg
  email    : nandomoreira.me@gmail.com
  url      : http://nandomoreira.me
  github   : http://github.com/nandomoreirame
  twitter  : http://twitter.com/nandomoreirame
  facebook : http://facebook.com/fernando.dev
  linkedin : http://linkedin.com/in/nandomoreirame

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
